language: node_js
node_js:
- node
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
- npm run compile
deploy:
  provider: npm
  email: tdillon25@gmail.com
  api_key:
    secure: jCDRcSSCM9SvOfiE681cTsKs8rr9SfVR8rxTtL/5QoSTIbBN0uWvsxPi2EHn7TMun4ZoLrQj1hgJFBYtjZ1EnEF7rHAu193tJfi2eJLQYpS5NlvXt74197kYWEf76bmCtxf+Qcb20FrD99QfCbv5nJnKqGaBECEioMrVIyPx0uQJOnEgfMTu4Q/QXw7XYySCrFRzKI0zPRarlBfrKp3xx0dyz72K4kcaA/RkGtu5oAqChpJ9pswiZfm4S2v4uJTxGeOrysRME2LtAVba5KPX55v9ne6fMyc/4L1fylhTDLp93rxtBJYYJLglh8LNffToYX2xnINiXylhZsau+EJVHLJqUtsda7dJqW4qkRix8kpkteJmO8MLLx7axPJJlxD0Lviyk67KSF7Tk8mxpEqGbXtXb2JsGwxVZ8Vdfbn/1WSDVmCXGgBnH43L5zKM1ZFr1qhxcEjalmZxTq3ediseCNzInJTaiR+wvIiezL/oV9YzYep+LTB19c3kYCh877mfDBCV4OWlB1YhT4qkgW8Qz0YM6x50m44nsRmj+BRxEvBDX/JwzJKOT/1O62yCRvs7SrgToJGTqkYgJLscDZ70SNfGvbw6DkpLzbqUYZzaUhWY5yKk12xmzgzkEy1W7djQ99BU0YSRTTw3w9cFuROegb11Kzzb2hDHhZR6GC7O2CU=
  on:
    tags: false
    repo: tdillon/rpsls
